# Generated by Django 5.2.1 on 2025-05-25 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('setor', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('abertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.acao')),
            ],
            options={
                'ordering': ['-data'],
                'unique_together': {('acao', 'data')},
            },
        ),
    ]
