# Generated by Django 5.2.1 on 2025-05-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotacao',
            name='abertura',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='fechamento',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='maxima',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='minima',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
    ]
