# Generated by Django 5.2.1 on 2025-05-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0002_alter_cotacao_abertura_alter_cotacao_fechamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotacao',
            options={},
        ),
        migrations.AddField(
            model_name='cotacao',
            name='reversao_detectada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='wma144',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='wma17',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='wma34',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='wma600',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='wma72',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='abertura',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='fechamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='maxima',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cotacao',
            name='minima',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
