# Generated by Django 5.2.1 on 2025-05-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0003_alter_cotacao_options_cotacao_reversao_detectada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotacao',
            old_name='wma600',
            new_name='wma602',
        ),
    ]
