# Generated by Django 5.2.1 on 2025-05-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0004_rename_wma600_cotacao_wma602'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacaoDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wma602', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('abaixo_wma', models.BooleanField()),
                ('percentual_diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('score_reversao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.acao')),
            ],
            options={
                'unique_together': {('acao', 'data')},
            },
        ),
    ]
