# Generated by Django 5.2.1 on 2025-05-28 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0005_recomendacaodiaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='nome',
            new_name='empresa',
        ),
    ]
