# Generated by Django 5.2.1 on 2025-05-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0006_rename_nome_acao_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='data_alvo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='fechamento_alvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
