# Generated by Django 5.2.1 on 2025-05-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0007_recomendacaodiaria_data_alvo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='ad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='obv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
