# Generated by Django 5.2.1 on 2025-05-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0008_cotacao_ad_cotacao_obv'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='cruzamento_medias',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='obv_crescente',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='subindo_3dias',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='volume_acima_media',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
