# Generated by Django 5.1.6 on 2025-06-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0009_recomendacaodiaria_cruzamento_medias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='posicao_alvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
