# Generated by Django 5.1.6 on 2025-06-03 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0010_recomendacaodiaria_posicao_alvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperacaoCarteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_compra', models.DateField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
                ('valor_total_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_venda', models.DateField(blank=True, null=True)),
                ('preco_venda_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.acao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.cliente')),
            ],
        ),
    ]
