# Generated by Django 5.2.1 on 2025-06-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0011_cliente_operacaocarteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacaoSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('fechamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wma602', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentual_diferenca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('subindo_3dias', models.BooleanField(blank=True, null=True)),
                ('cruzamento_medias', models.BooleanField(blank=True, null=True)),
                ('volume_acima_media', models.BooleanField(blank=True, null=True)),
                ('obv_crescente', models.BooleanField(blank=True, null=True)),
                ('score_reversao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atingiu_alvo', models.BooleanField(blank=True, null=True)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacoes.acao')),
            ],
            options={
                'unique_together': {('acao', 'data')},
            },
        ),
    ]
