# Generated by Django 5.2.1 on 2025-06-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0012_recomendacaosimulada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='media_volume_20d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='retorno_5d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='rsi_14',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
