# Generated by Django 5.2.1 on 2025-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0014_recomendacaosimulada_media_volume_20d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='origem',
            field=models.CharField(choices=[('score', 'Score'), ('ia', 'IA')], default='score', max_length=10),
        ),
    ]
