# Generated by Django 5.2.1 on 2025-06-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0015_recomendacaodiaria_origem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recomendacaodiaria',
            unique_together={('acao', 'data', 'origem')},
        ),
    ]
