# Generated by Django 5.2.1 on 2025-06-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0016_alter_recomendacaodiaria_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='alvo_sugerido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
