# Generated by Django 5.2.1 on 2025-06-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0017_recomendacaodiaria_alvo_sugerido'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='perc_alvo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
