# Generated by Django 5.2.1 on 2025-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0018_recomendacaodiaria_perc_alvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotacao',
            name='retorno_5d',
        ),
        migrations.RemoveField(
            model_name='cotacao',
            name='reversao_detectada',
        ),
        migrations.AddField(
            model_name='cotacao',
            name='fechamento_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='max_5dias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='rsi_14_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='target_compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotacao',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
