# Generated by Django 5.2.1 on 2025-06-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0019_remove_cotacao_retorno_5d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='atr',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
