# Generated by Django 5.2.1 on 2025-06-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacoes', '0020_cotacao_atr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='fechamento',
        ),
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='percentual_diferenca',
        ),
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='posicao_alvo',
        ),
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='score_reversao',
        ),
        migrations.RemoveField(
            model_name='recomendacaodiaria',
            name='subindo_3dias',
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='perc_alvo_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recomendacaodiaria',
            name='probabilidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='recomendacaodiaria',
            name='alvo_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recomendacaodiaria',
            name='origem',
            field=models.CharField(choices=[('score', 'Score'), ('ia', 'IA')], default='ia', max_length=10),
        ),
        migrations.AlterField(
            model_name='recomendacaodiaria',
            name='perc_alvo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
